python3 simulate.py -w 0 -l 'Palo Alto' -tod 'morning'
python3 simulate.py -w 1 -l 'Palo Alto' -tod 'morning'
python3 simulate.py -w 2 -l 'Palo Alto' -tod 'morning'
python3 simulate.py -w 3 -l 'Palo Alto' -tod 'morning'
python3 simulate.py -w 4 -l 'Palo Alto' -tod 'morning'
python3 simulate.py -w 5 -l 'Palo Alto' -tod 'morning'
python3 simulate.py -w 0 -l 'Palo Alto' -tod 'midday'
python3 simulate.py -w 1 -l 'Palo Alto' -tod 'midday'
python3 simulate.py -w 2 -l 'Palo Alto' -tod 'midday'
python3 simulate.py -w 3 -l 'Palo Alto' -tod 'midday'
python3 simulate.py -w 4 -l 'Palo Alto' -tod 'midday'
python3 simulate.py -w 5 -l 'Palo Alto' -tod 'midday'
python3 simulate.py -w 0 -l 'Palo Alto' -tod 'earlyafternoon'
python3 simulate.py -w 1 -l 'Palo Alto' -tod 'earlyafternoon'
python3 simulate.py -w 2 -l 'Palo Alto' -tod 'earlyafternoon'
python3 simulate.py -w 3 -l 'Palo Alto' -tod 'earlyafternoon'
python3 simulate.py -w 4 -l 'Palo Alto' -tod 'earlyafternoon'
python3 simulate.py -w 5 -l 'Palo Alto' -tod 'earlyafternoon'
python3 simulate.py -w 0 -l 'Palo Alto' -tod 'lateafternoon'
python3 simulate.py -w 1 -l 'Palo Alto' -tod 'lateafternoon'
python3 simulate.py -w 2 -l 'Palo Alto' -tod 'lateafternoon'
python3 simulate.py -w 3 -l 'Palo Alto' -tod 'lateafternoon'
python3 simulate.py -w 4 -l 'Palo Alto' -tod 'lateafternoon'
python3 simulate.py -w 5 -l 'Palo Alto' -tod 'lateafternoon'
python3 simulate.py -w 0 -l 'Boston' -tod 'lateafternoon'
python3 simulate.py -w 1 -l 'Boston' -tod 'lateafternoon'
python3 simulate.py -w 2 -l 'Boston' -tod 'lateafternoon'
python3 simulate.py -w 3 -l 'Boston' -tod 'lateafternoon'
python3 simulate.py -w 4 -l 'Boston' -tod 'lateafternoon'
python3 simulate.py -w 5 -l 'Boston' -tod 'lateafternoon'
python3 simulate.py -w 0 -l 'Boston' -tod 'earlyafternoon'
python3 simulate.py -w 1 -l 'Boston' -tod 'earlyafternoon'
python3 simulate.py -w 2 -l 'Boston' -tod 'earlyafternoon'
python3 simulate.py -w 3 -l 'Boston' -tod 'earlyafternoon'
python3 simulate.py -w 4 -l 'Boston' -tod 'earlyafternoon'
python3 simulate.py -w 5 -l 'Boston' -tod 'earlyafternoon'
python3 simulate.py -w 0 -l 'Boston' -tod 'midday'
python3 simulate.py -w 1 -l 'Boston' -tod 'midday'
python3 simulate.py -w 2 -l 'Boston' -tod 'midday'
python3 simulate.py -w 3 -l 'Boston' -tod 'midday'
python3 simulate.py -w 4 -l 'Boston' -tod 'midday'
python3 simulate.py -w 5 -l 'Boston' -tod 'midday'
python3 simulate.py -w 0 -l 'Boston' -tod 'morning'
python3 simulate.py -w 1 -l 'Boston' -tod 'morning'
python3 simulate.py -w 2 -l 'Boston' -tod 'morning'
python3 simulate.py -w 3 -l 'Boston' -tod 'morning'
python3 simulate.py -w 4 -l 'Boston' -tod 'morning'
python3 simulate.py -w 5 -l 'Boston' -tod 'morning'
python3 simulate.py -w 0 -l 'Osh Kosh' -tod 'morning'
python3 simulate.py -w 1 -l 'Osh Kosh' -tod 'morning'
python3 simulate.py -w 2 -l 'Osh Kosh' -tod 'morning'
python3 simulate.py -w 3 -l 'Osh Kosh' -tod 'morning'
python3 simulate.py -w 4 -l 'Osh Kosh' -tod 'morning'
python3 simulate.py -w 5 -l 'Osh Kosh' -tod 'morning'
python3 simulate.py -w 0 -l 'Osh Kosh' -tod 'midday'
python3 simulate.py -w 1 -l 'Osh Kosh' -tod 'midday'
python3 simulate.py -w 2 -l 'Osh Kosh' -tod 'midday'
python3 simulate.py -w 3 -l 'Osh Kosh' -tod 'midday'
python3 simulate.py -w 4 -l 'Osh Kosh' -tod 'midday'
python3 simulate.py -w 5 -l 'Osh Kosh' -tod 'midday'
python3 simulate.py -w 0 -l 'Osh Kosh' -tod 'earlyafternoon'
python3 simulate.py -w 1 -l 'Osh Kosh' -tod 'earlyafternoon'
python3 simulate.py -w 2 -l 'Osh Kosh' -tod 'earlyafternoon'
python3 simulate.py -w 3 -l 'Osh Kosh' -tod 'earlyafternoon'
python3 simulate.py -w 4 -l 'Osh Kosh' -tod 'earlyafternoon'
python3 simulate.py -w 5 -l 'Osh Kosh' -tod 'earlyafternoon'
python3 simulate.py -w 0 -l 'Osh Kosh' -tod 'lateafternoon'
python3 simulate.py -w 1 -l 'Osh Kosh' -tod 'lateafternoon'
python3 simulate.py -w 2 -l 'Osh Kosh' -tod 'lateafternoon'
python3 simulate.py -w 3 -l 'Osh Kosh' -tod 'lateafternoon'
python3 simulate.py -w 4 -l 'Osh Kosh' -tod 'lateafternoon'
python3 simulate.py -w 5 -l 'Osh Kosh' -tod 'lateafternoon'
python3 simulate.py -w 0 -l 'Reno Tahoe' -tod 'morning'
python3 simulate.py -w 1 -l 'Reno Tahoe' -tod 'morning'
python3 simulate.py -w 2 -l 'Reno Tahoe' -tod 'morning'
python3 simulate.py -w 3 -l 'Reno Tahoe' -tod 'morning'
python3 simulate.py -w 4 -l 'Reno Tahoe' -tod 'morning'
python3 simulate.py -w 5 -l 'Reno Tahoe' -tod 'morning'
python3 simulate.py -w 0 -l 'Reno Tahoe' -tod 'midday'
python3 simulate.py -w 1 -l 'Reno Tahoe' -tod 'midday'
python3 simulate.py -w 2 -l 'Reno Tahoe' -tod 'midday'
python3 simulate.py -w 3 -l 'Reno Tahoe' -tod 'midday'
python3 simulate.py -w 4 -l 'Reno Tahoe' -tod 'midday'
python3 simulate.py -w 5 -l 'Reno Tahoe' -tod 'midday'
python3 simulate.py -w 0 -l 'Reno Tahoe' -tod 'earlyafternoon'
python3 simulate.py -w 1 -l 'Reno Tahoe' -tod 'earlyafternoon'
python3 simulate.py -w 2 -l 'Reno Tahoe' -tod 'earlyafternoon'
python3 simulate.py -w 3 -l 'Reno Tahoe' -tod 'earlyafternoon'
python3 simulate.py -w 4 -l 'Reno Tahoe' -tod 'earlyafternoon'
python3 simulate.py -w 5 -l 'Reno Tahoe' -tod 'earlyafternoon'
python3 simulate.py -w 0 -l 'Reno Tahoe' -tod 'lateafternoon'
python3 simulate.py -w 1 -l 'Reno Tahoe' -tod 'lateafternoon'
python3 simulate.py -w 2 -l 'Reno Tahoe' -tod 'lateafternoon'
python3 simulate.py -w 3 -l 'Reno Tahoe' -tod 'lateafternoon'
python3 simulate.py -w 4 -l 'Reno Tahoe' -tod 'lateafternoon'
python3 simulate.py -w 5 -l 'Reno Tahoe' -tod 'lateafternoon'
